name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js and npm
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: npm install
        run: |
          npm ci

      - name: npm test
        run: |
          npm run build
          npm run lint
          npm run tsc
          npm test
